[global]
showWarningOnDirectExecution = true

[logger]
level = "info"

[client]
showErrorDetails = true
showSidebarNavigation = false

[runner]
fastReruns = true

[server]
runOnSave = true
port = 8501

[theme]
primaryColor="#1ED760"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="monospace"
